// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuNAq2RDdjYbW-tF9NLDF471113CrptOw',
    appId: '1:778516764210:web:67b95b01a67f0f13e54e2b',
    messagingSenderId: '778516764210',
    projectId: 'otobix-firebase-project',
    authDomain: 'otobix-firebase-project.firebaseapp.com',
    storageBucket: 'otobix-firebase-project.firebasestorage.app',
    measurementId: 'G-D7B18WKCFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjfSy6Qr7NZTZOfOVRDToGXqI77_vtkg',
    appId: '1:778516764210:android:605f5f02641cbb2ce54e2b',
    messagingSenderId: '778516764210',
    projectId: 'otobix-firebase-project',
    storageBucket: 'otobix-firebase-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWmkVtVwp6-rLv5_xvBvvDCWWN2Zd33RM',
    appId: '1:778516764210:ios:e15746782fbfebb0e54e2b',
    messagingSenderId: '778516764210',
    projectId: 'otobix-firebase-project',
    storageBucket: 'otobix-firebase-project.firebasestorage.app',
    iosBundleId: 'com.example.otobixFrontend',
  );
}
