// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQhwUma78s5ZoBYcQt72sJYSzIorfR6E',
    appId: '1:349730100681:web:692a6862c415324d5f0418',
    messagingSenderId: '349730100681',
    projectId: 'otobix-auction-app',
    authDomain: 'otobix-auction-app.firebaseapp.com',
    storageBucket: 'otobix-auction-app.firebasestorage.app',
    measurementId: 'G-PX3N2JK5KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkjgRe_95A3dz7gFh0VctlK3nS_XLEhA4',
    appId: '1:349730100681:android:6df6b765a538e9985f0418',
    messagingSenderId: '349730100681',
    projectId: 'otobix-auction-app',
    storageBucket: 'otobix-auction-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgHQPGIBrufqVQbei3Rb-Z6mG_a8hDCBs',
    appId: '1:349730100681:ios:16922e77f531379e5f0418',
    messagingSenderId: '349730100681',
    projectId: 'otobix-auction-app',
    storageBucket: 'otobix-auction-app.firebasestorage.app',
    iosBundleId: 'com.example.otobixFrontend',
  );

}