
default_platform(:ios)
platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Build the app (with automatic signing)
    build_app(
      scheme: "Runner",                     # Xcode scheme name
      export_method: "app-store",           # Export for App Store
      include_bitcode: false
    )
    # Upload to TestFlight using API key
    upload_to_testflight(
      api_key: app_store_connect_api_key(
        key_id: ENV["APP_STORE_KEY_ID"],
        issuer_id: ENV["APP_STORE_ISSUER_ID"],
        key_content: ENV["APP_STORE_P8_KEY"],
        is_key_content_base64: false
      ),
      skip_waiting_for_build_processing: true
    )
  end
end





# default_platform(:ios)

# platform :ios do
#   lane :codesign_setup do
#     # One-time bootstrap to create and upload certs/profiles to the ios_signing branch
#     match(
#       type: "appstore",
#       git_url: "https://github.com/SagheerHussain/otobix-app.git",              # we'll set in CI; locally you can hardcode too
#       git_branch: "ios_signing",
#       api_key_path: "fastlane/asc_api_key_json_for_github_actions.json",
#       app_identifier: "com.otobix.auctionapp"
#       team_id: "734JT7MU9R",             # or hardcode your team
#       readonly: false
#     )
#   end

#   lane :codesign do
#     # CI/read-only usage (downloads profiles/certs created above)
#     match(
#       type: "appstore",
#       git_url: "https://github.com/SagheerHussain/otobix-app.git",
#       git_branch: "ios_signing",
#       api_key_path: "fastlane/asc_api_key_json_for_github_actions.json",
#       app_identifier: "com.otobix.auctionapp",
#       team_id: "734JT7MU9R",
#       readonly: false
#     )
#   end

#   lane :build do
#     # typical build lane (optional)
#     gym(
#       workspace: "Runner.xcworkspace",
#       scheme: "Runner",
#       configuration: "Release",
#       export_method: "app-store"
#     )
#   end

#   lane :release do
#     # upload to TestFlight (optional)
#     pilot(api_key_path: "fastlane/asc_api_key_json_for_github_actions.json")
#   end
# end
